Add External Resources to hold URLs to redirect from conference
builderscon/octav pull request #192
Opened 2016-12-18 19:05 UTC by richard-imaoka

* v1/external_resource/create
* v1/external_resource/lookup
* v1/external_resource/list
* v1/external_resource/update
* v1/external_resource/delete

がちゃんと動く事と、日本語を入れた時に国際化も期待どおりであることを確認しています。

コミットを幾つかにわけたので、特に見ていただきたいのは:

* Define external_resource models
* Association between conference and external resources

この２つです。あとは

* Auto generated files for external_resources
* Update bindings

の２つが自動生成

* Add required changes from auto generated code

これがほぼ定型のコードのようなので、多分大丈夫だと思っています。（もちろんこれらについてもレビューしていただけるなら大変ありがたいです。）

2016-12-18 19:19 UTC, richard-imaoka commented
Refs
* builderscon/conf.builderscon.io#178 
* builderscon/conf.builderscon.io#193

すいません、adminの方にはまだ手をつけることができていません
Refs builderscon/admin.builderscon.io#36

2016-12-22 00:32 UTC, lestrrat commented on octav/service/external_resource.go
> +	if err := c.Get(key, &ids); err == nil {
多分conference.goあたりからもってきたんだと思うけど、新しいコードはこっちみたいにGetOrSet使うほうがいいと思います。この辺りは歴史的経緯でそろってない感じです

https://github.com/builderscon/octav/blob/master/octav/service/session.go#L438-L440

2016-12-23 01:52 UTC, richard-imaoka commented on octav/service/external_resource.go
> +	if err := c.Get(key, &ids); err == nil {
GetOrSet()に変更しました

2016-12-23 01:53 UTC, richard-imaoka commented
頂いたコメント反映しました。Ready for reviewです！（コミット数やたらに増えてすみません）

2016-12-23 05:12 UTC, lestrrat requested changes
キャッシュまわりに結構深刻な問題がありそうなのでその辺りを直さないとマージはできなさそう…

2016-12-23 05:12 UTC, lestrrat commented on octav/db/external_resource.go
> +	stmt.WriteString(`SELECT `)
staticなSQLなのでlibraryを使うと良さそう。

2016-12-23 05:12 UTC, lestrrat commented on octav/service/external_resource.go
> +	*result = *(x.(*model.ExternalResourceList))
あれ、GetOrSetに渡してるresultにすでに情報入ってない？こんな型変換を必要とした記憶がない…

2016-12-23 05:12 UTC, lestrrat commented on octav/sql/octav.sql
> +CREATE TABLE external_resources (
多分sort_orderをつける必要があると思います。

2016-12-23 05:12 UTC, lestrrat commented on octav/service/external_resource.go
> +	key := c.Key("ExternalResource", "ListFromPayload", cid)
キャッシュキーがメソッド名と連携してないので混乱をきたしそう

2016-12-23 05:12 UTC, lestrrat commented on octav/service/interface.go
> +type ExternalResourceSvc struct{}
Create/Update/Delete時にList系のキャッシュの更新をしてない。

2016-12-23 05:12 UTC, lestrrat commented on octav/service/external_resource.go
> +			if err := v.Decorate(tx, &l[i], trustedCall, lang); err != nil {
キャッシュする時にDecorateした結果を入れてると、lang=enを先にキャッシュしちゃうとlang=jaでアクセスした時にlang=enの結果が返っちゃう。ここでDecorateをするならキャッシュキーにlangを含めないといけない。
けど、後でDecorateを呼んでる場所がある気がするので、そっちで呼ぶならそもそもこれはいらないはず。

あと、場合によりけりだけど、リスト系はIDだけキャッシュしておいて、実体はPKでlookupした時と同じキャッシュを参照する、という手も。他のところで似たような事をしていたような記憶が…

2016-12-24 06:13 UTC, richard-imaoka commented on octav/service/external_resource.go
> +	*result = *(x.(*model.ExternalResourceList))
すいません、他のところは新しいコミットで直したつもりなのですが、ここだけがどうしてもわかりませんでした...
* [service/blog_entry.go](https://github.com/builderscon/octav/blob/richard-wip-external-resources/octav/service/blog_entry.go#L206)と[service/session.go](https://github.com/builderscon/octav/blob/richard-wip-external-resources/octav/service/session.go#L468)で同じような型変換をしています
* あと、GetOrSet()に渡してるresultに結果が入るのでしょうか...? GetOrSet()の戻り値として結果が返されると思ったのですが...
* それで、xからresultにassignするときに、上記の型変換をしないと「invalid indirect of x (type interface {})」とかいうメッセージが出て、すみません型の話よくわかってなくて力尽きました

2016-12-24 06:32 UTC, lestrrat commented on octav/service/external_resource.go
> +	*result = *(x.(*model.ExternalResourceList))
多分いらないと思うな＞session.go/blog_entry.go ただの「考えないでコピペ」だと思います。試してみよう…

2016-12-24 06:51 UTC, lestrrat commented on octav/service/external_resource.go
> +	*result = *(x.(*model.ExternalResourceList))
あー、わかった。これ、Setするときに第2引数が値を受け取るためにポインタなのか、ポインタを格納しないのか、を判別不能だから、このままだと期待通りに動かないんだ。

面倒くさいのでrichardさんのコミットのままでいきましょう！

2016-12-24 06:52 UTC, lestrrat commented on octav/service/external_resource.go
> +	*result = *(x.(*model.ExternalResourceList))
これで終了なら一応本スレに「終了」コメント書いて置いてください〜

2016-12-24 07:04 UTC, richard-imaoka commented
octav側はこれで終了のつもりです、octavがこれでよければ引き続き、confとadminに取り掛かります。

2016-12-24 07:49 UTC, lestrrat commented
是非adminがわを…！

2016-12-24 07:53 UTC, richard-imaoka commented
了解で。.が、admin触るの相当久しぶりなので、ちょっとお時間いただきたいです。なんとか月曜までに終われば,,,,

2016-12-24 07:55 UTC, lestrrat commented
まぁconfとほぼ一緒ですよ。flaskで書き直しちゃったし

2016-12-24 09:11 UTC, lestrrat approved these changes

2017-01-03 22:10 UTC, richard-imaoka commented
まことに申し訳ないです。
api.jsonで以下の間違いを見つけたので、最新の追加コミットで修正しました。

* external resourceにconference_idを追加(lookupで見えるように)
* updateの時はconference_idは必須ではない、external resource自体のidが必須

2017-01-04 01:29 UTC, merged

2017-01-04 01:51 UTC, richard-imaoka commented
ウェエエエエエエイ！！octavに初merge!

@lestrrat さん、スーパーありがとうございます！！辛抱づよくレビューしていただいて本当に感謝です。

2017-01-04 01:52 UTC, lestrrat commented
あ、そうなの？ｗ＞初merge 👍